# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('present_day1', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21161')),
                ('present_day2', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21162')),
                ('present_day3', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21163')),
                ('present_day4', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21164')),
                ('present_day5', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21165')),
                ('present_day6', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21166')),
                ('present_day7', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21167')),
                ('present_day8', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21168')),
                ('present_day9', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21169')),
                ('present_day10', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211610')),
                ('present_day11', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211611')),
                ('present_day12', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211612')),
                ('present_day13', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211613')),
                ('present_day14', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211614')),
                ('present_day15', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211615')),
                ('present_day16', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211616')),
                ('present_day17', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211617')),
                ('present_day18', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211618')),
                ('present_day19', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211619')),
                ('present_day20', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211620')),
                ('present_day21', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211621')),
                ('present_day22', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211622')),
                ('present_day23', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211623')),
                ('present_day24', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211624')),
                ('present_day25', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211625')),
                ('present_day26', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211626')),
                ('present_day27', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211627')),
                ('present_day28', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211628')),
                ('present_day29', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211629')),
                ('present_day30', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211630')),
                ('present_day31', models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211631')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month=b'date', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041c\u0456\u0441\u044f\u0447\u043d\u0438\u0439 \u0416\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u041c\u0456\u0441\u044f\u0447\u043d\u0456 \u0416\u0443\u0440\u043d\u0430\u043b\u0438',
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='examdate',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0456 \u0447\u0430\u0441 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u043d\u044f\n\u0443 \u0444\u043e\u0440\u043c\u0430\u0442\u0456 \u0420\u0420\u0420\u0420-\u041c\u041c-\u0414\u0414 \u0413\u0413:\u0425\u0425:\u0421\u0421'),
        ),
    ]
