# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default=b'', max_length=13, verbose_name='Mobile Phone'),
        ),
    ]
