# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0002_auto_20161031_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport_id',
            field=models.CharField(blank=True, default=b'', max_length=8, verbose_name='Passport ID'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='User Photo'),
        ),
    ]
